## workflow build config

# id and name for the workflow (bundle id = domain.id)
id: alfred-transmit-workflow

# base domain
domain: com.tumblr.ramiroaraujo

name: Transmit
description: Connect to Transmit Favorites
created_by: Ramiro Araujo
website: https://github.com/ramiroaraujo/alfred-transmit-workflow
readme: readme

## development config

# path is the relative path to the workflow in the project root
path: workflow

# If you are using Alfred's advanced Dropbox sync, indicate the path shown in
# Alfred Preferences > Advanced > Syncing:
dropbox: ~/Dropbox